APPS = {"HARMONY": "HARMONY"}
HARMONY = "HARMONY"

APP = 'HARMONY'
app = APP

CONTACT_ADDRESS = "@bigb4ever"

H_ELECTED = "Elected"
H_ELIGIBLE = "Eligible"
H_NOT_ELIGIBLE = "NotEligible"

ALL_ELIGIBLE_CLAUSE = "('Elected','Eligible') "
ALL_ELIGIBLE = "AllEligible"
ALL_FEE_INCREASE = "FeeIncrease"
ALL_STATUS = "All"

H_EPOCH_MODE = "EPOCH"
H_HOUR_MODE = "HOUR"

H_HISTORY_NETWORK='Network'
H_HISTORY_VALIDATOR='Validator'
H_HISTORY_VALIDATOR_PERF='ValPerf'
H_HISTORY_ADDRESS='Address'
H_HISTORY_NETWORK_VALUES = ["totalStake", "circulatingSupply", "currentRewardRate", "totalValidators", "btcPrice", "medianRawStake"]
H_HISTORY_ADDRESS_VALUES= ["totalStake", "totalBalance", "totalRewards"]


SYNC_STATUS_EPOCH_FOR_SIGN='EpochForSignSync'
H_ADDRESS_HISTORY_SYNC='AddressHistory'
H_MIN_BAL_FOR_HISTORY="1000"
H_MIN_BLOCKS_FOR_CURRENT_EPOCH_APR=500
H_POOL_ID_SS = 42
H_POOL_ID_OTHER = 151

TG_BOT_NAME_1 = "@SSHDevBot"
TG_BOT_NAME_2 = "@HarmonyAnalyticsBot"

CROSS_LINK_DELAY_TOLERANCE = 100
MIN_BLOCKS_BLS_KEY_NOTIFICATIONS = 500
MAX_BLOCKS_BLS_KEY_NOTIFICATIONS = 32000
MIN_BLOCKS_UNDERBID_NOTIFICATIONS = 1000
MAX_BLOCKS_UNDERBID_NOTIFICATIONS = 32000
PROP_KEY_TG_ID = "TG_ID"
