APPS = {"HARMONY": "HARMONY"}

HARMONY = "HARMONY"

CONTACT_ADDRESS = "@bigb4ever"

H_ELECTED = "Elected"
H_ELIGIBLE = "Eligible"
H_NOT_ELIGIBLE = "NotEligible"

ALL_ELIGIBLE_CLAUSE = "('Elected','Eligible') "
ALL_ELIGIBLE = "AllEligible"
ALL_STATUS = "All"

H_EPOCH_MODE = "EPOCH"
H_HOUR_MODE = "HOUR"

H_BLOCKS_IN_EPOCH = 32768
H_BLOCK_TIME = 2
# (86400 * 365) /(16384 * 8)
H_EPOCHS_IN_YEAR = round((86400 * 365) /(H_BLOCKS_IN_EPOCH * H_BLOCK_TIME))
H_FIRST_EPOCH=190
H_EPOCHS_FOR_AVERAGE=30

H_HISTORY_NETWORK='Network'
H_HISTORY_VALIDATOR='Validator'
H_HISTORY_ADDRESS='Address'
H_HISTORY_NETWORK_VALUES = ["totalStake", "circulatingSupply", "currentRewardRate", "totalValidators", "btcPrice", "medianRawStake"]
H_HISTORY_ADDRESS_VALUES= ["totalStake", "totalBalance", "totalRewards"]


H_ADDRESS_HISTORY_SYNC='AddressHistory'
H_MIN_BAL_FOR_HISTORY="1000"
H_MIN_BLOCKS_FOR_CURRENT_EPOCH_APR=800
H_POOL_ID_SS = 42

H_EVENT_FEE_INCREASE = "Fee_Increase"
H_EVENT_FEE_DECREASE = "Fee_Decrease"
H_EVENT_EDIT_VALIDATOR = "EditValidator"
H_CREATE_VALIDATOR = "CreateValidator"
H_EVENT_DELEGATE = "Delegate"
H_EVENT_UNDELEGATE = "Undelegate"
H_EVENT_COLLECT_REWARDS = "CollectRewards"
H_EVENT_BLS_KEY_ADDED = "BLSKeyAdded"
H_EVENT_BLS_KEY_REMOVED = "BLSKeyRemoved"

EVENT_LAST_SYNCED_EVENT_BLOCK_HEIGHT = "harmonyLastSyncedEventBlockHeight"

H_EVENT_NOTIFICATIONS_LARGE_MIN = 1000000
LOW_SIGN_THRESHOLD = "98"
LOW_ERI_THRESHOLD = "0.9"
KEY_BAD_PERF_INDEX_THRESHOLD = "0.98"

NOTIFICATION_TYPE_REGULAR_TX_FROM = "RegularTxFrom"
NOTIFICATION_TYPE_REGULAR_TX_TO = "RegularTxTo"
NOTIFICATION_TYPE_LOW_SIGN = "LowSignRate"
NOTIFICATION_TYPE_LOW_ERI = "LowERI"
NOTIFICATION_TYPE_GOOD_SIGN = "GoodSignRate"
NOTIFICATION_TYPE_GOOD_ERI = "GoodERI"
NOTIFICATION_TYPE_KEY_PERF_BAD = "KeyPerfBad"
NOTIFICATION_TYPE_KEY_PERF_GOOD = "KeyPerfGood"
NOTIFICATION_TYPE_UNELECTED = "ValUnelected"
NOTIFICATION_TYPE_PARTIALLY_ELECTED = "ValPartElected"
NOTIFICATION_TYPE_HIGH_BID = "ValHighBid"
NOTIFICATION_TYPE_UNDER_BID_OPP = "ValUnderBidOpp"
NOTIFICATION_TYPE_UNDER_BID_OPP_END = "ValUnderBidOppEnd"

NOTIFICATION_TYPE_SELF_BOND_REMOVED = "SelfBondRemoved"
NOTIFICATION_TYPE_UNELECTED_FOR_LONG = "ValUnelectedLong"

NOTIFICATION_TYPE_RISK_UNELECTED = "RiskValUnelected"
NOTIFICATION_TYPE_RISK_PARTIALLY_ELECTED = "RiskValPartElected"
NOTIFICATION_TYPE_RISK_HIGH_BID = "RiskValHighBid"
NOTIFICATION_TYPE_RISK_UNELECTED_END = "RiskValUnelectedEnd"
NOTIFICATION_TYPE_RISK_PARTIALLY_ELECTED_END = "RiskValPartElectedEnd"
NOTIFICATION_TYPE_RISK_HIGH_BID_END = "RiskValHighBidEnd"
NOTIFICATION_TYPE_EPOCH_ENDING_SOON = "EpochEndingSoon"
NOTIFICATION_TYPE_BLS_KEY_ON_OLD_VERSION = "BlsKeyOldVersion"

KEY_URL = "https://harmony.smartstake.io/key/{}/{}"
ELECTIONS_URL = "https://api.stake.hmny.io/networks/mainnet/staking_network_info"
# https://hmny-t.co/networks/mainnet/staking_network_info
MAX_SLOTS = 640

EPOCH_ALERT_1_HR_MINIMUM_TIME_LEFT = 64 * 60
EPOCH_ALERT_30_MIN_MINIMUM_TIME_LEFT = 33 * 60
EPOCH_ALERT_15_MIN_MINIMUM_TIME_LEFT = 18 * 60
EPOCH_ALERT_1_HR_EVENT = "EpochAlert1Hr"
EPOCH_ALERT_30_MIN_EVENT = "EpochAlert30Min"
EPOCH_ALERT_15_MIN_EVENT = "EpochAlert15Min"

TX_REGULAR = "regular"
TX_STAKING = "staking"
TX_STATUS_SUCCESS = "Success"

VERSION_ALERT_RANGE = 10
VERSION_ALERT_EPOCH_PROP = "harmonyMandatoryVersionEffectiveEpoch"
VERSION_ALERT_MANDATORY_PROP = "harmonyMandatoryVersion"
