# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!


# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

# https://serverless-stack.com/chapters/stages-in-serverless-framework.html
custom:
  myStage: ${opt:stage, self:provider.stage}
  config: ${file(../haconfig.${opt:stage, self:provider.stage}.json)}
  myEnvironment:
    ENV: ${self:custom.config.ENV}
    DB_SCHEMA_NAME: ${self:custom.config.DB_SCHEMA_NAME}
    DB_ENDPOINT: ${self:custom.config.DB_ENDPOINT}
    DB_PORT: ${self:custom.config.DB_PORT}
    DB_USERNAME: ${self:custom.config.DB_USERNAME}
    DB_PASSWORD: ${self:custom.config.DB_PASSWORD}
    H_TELEGRAM_TOKEN: ${self:custom.config.H_TELEGRAM_TOKEN}
    SECURITY_KEY_1: ${self:custom.config.SECURITY_KEY_1}
    SECURITY_KEY_2: ${self:custom.config.SECURITY_KEY_2}
    DEFAULT_POOL_ID: ${self:custom.config.DEFAULT_POOL_ID}
    REGION: ${self:custom.config.REGION}
    SERVICE_NAME:
      test: ha
      prod: ha
      dev: ha
service: ${self:custom.myEnvironment.SERVICE_NAME.${self:custom.myStage}}

provider:
  name: aws
  memorySize: 128
  versionFunctions: false
  runtime: python3.6
  stage: dev
  environment:
    ENV: ${self:custom.myEnvironment.ENV}
    DB_SCHEMA_NAME: ${self:custom.myEnvironment.DB_SCHEMA_NAME}
    DB_ENDPOINT: ${self:custom.myEnvironment.DB_ENDPOINT}
    DB_PORT: ${self:custom.myEnvironment.DB_PORT}
    DB_USERNAME: ${self:custom.myEnvironment.DB_USERNAME}
    DB_PASSWORD: ${self:custom.myEnvironment.DB_PASSWORD}
    H_TELEGRAM_TOKEN: ${self:custom.myEnvironment.H_TELEGRAM_TOKEN}
    SECURITY_KEY_1: ${self:custom.myEnvironment.SECURITY_KEY_1}
    SECURITY_KEY_2: ${self:custom.myEnvironment.SECURITY_KEY_2}
    DEFAULT_POOL_ID: ${self:custom.myEnvironment.DEFAULT_POOL_ID}
  region: ${self:custom.myEnvironment.REGION}

functions:
  listData:
    handler: listData.lambda_handler
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: listData
          method: get
          cors:
            origin: '*'
  validators:
    handler: validators.lambda_handler
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: validators
          method: get
          cors:
            origin: '*'
  harmonyUpdateData:
    handler: harmonyUpdateData.lambda_handler
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: harmonyUpdateData
          method: post
          cors:
            origin: '*'
  sendNotifications:
    handler: hTgNotificationSync.lambda_handler
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: sendNotifications
          method: post
          cors:
            origin: '*'
  harmonyValSync:
    handler: harmonyValSync.lambda_handler
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: harmonyValSync
          method: post
          cors:
            origin: '*'
  hTgBot:
    handler: hTgBot.tgHandler
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: hTgBot
          method: post
          cors:
            origin: '*'
  temp:
    handler: temp.lambda_handler
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: temp
          method: post
          cors:
            origin: '*'

plugins:
  - serverless-python-requirements
  - serverless-openapi-documentation
